# Generated by Django 5.1.8 on 2025-04-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
