# Generated by Django 5.1.8 on 2025-05-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0011_alter_branch_branch_name'),
        ('schedule', '0001_initial'),
        ('semester', '0004_alter_activeclasssemester_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='batch',
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='active_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='semester.activeclasssemester'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='director.branch'),
        ),
    ]
