# Generated by Django 5.1.8 on 2025-05-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0011_alter_branch_branch_name'),
        ('schedule', '0002_remove_classschedule_batch_and_more'),
        ('semester', '0004_alter_activeclasssemester_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassSchedule',
            new_name='ClassSchedule2',
        ),
    ]
