# Generated by Django 5.1.8 on 2025-05-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0011_alter_branch_branch_name'),
        ('schedule', '0003_rename_classschedule_classschedule2'),
        ('semester', '0004_alter_activeclasssemester_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassSchedule2',
            new_name='ClassSchedule',
        ),
    ]
