# Generated by Django 5.1.8 on 2025-05-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0011_alter_branch_branch_name'),
        ('schedule', '0004_rename_classschedule2_classschedule'),
        ('semester', '0004_alter_activeclasssemester_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_semester2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules2', to='semester.activeclasssemester')),
                ('branch2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers2', to='director.branch')),
                ('day2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.day')),
                ('period2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.periodslot')),
                ('subject2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='semester.semestersubject')),
                ('teacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.teacher')),
            ],
            options={
                'unique_together': {('active_semester2', 'day2', 'period2')},
            },
        ),
    ]
