# Generated by Django 5.2 on 2025-04-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='year',
            new_name='batch_name',
        ),
    ]
