# Generated by Django 5.1.8 on 2025-05-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_rename_year_batch_batch_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hod',
            old_name='last_name',
            new_name='hod_name',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='first_name',
        ),
        migrations.AddField(
            model_name='branch',
            name='hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='director.hod'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='director.batch'),
        ),
    ]
