# Generated by Django 5.1.8 on 2025-05-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_rename_last_name_hod_hod_name_remove_hod_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='branch_name',
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='email',
            new_name='hod_email',
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='phone_number',
            new_name='hod_phone_number',
        ),
    ]
