# Generated by Django 5.1.8 on 2025-05-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_rename_name_branch_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_username', models.CharField(max_length=150, unique=True)),
                ('teacher_password', models.CharField(max_length=128)),
                ('teacher_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('teacher_phone_number', models.CharField(max_length=15)),
                ('is_hod', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='hod',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_hod': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='director.teacher'),
        ),
        migrations.DeleteModel(
            name='HOD',
        ),
    ]
