# Generated by Django 5.1.8 on 2025-05-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0006_alter_teacher_teacher_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
