# Generated by Django 5.1.8 on 2025-05-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0007_alter_teacher_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
