# Generated by Django 5.1.8 on 2025-05-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0008_alter_teacher_teacher_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_phone_number',
            new_name='teacher_phone',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='hod',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='director.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_of_branch', to='director.teacher'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
