# Generated by Django 5.1.8 on 2025-05-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0010_remove_batch_batch_branch_classgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
