# Generated by Django 5.1.8 on 2025-05-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0010_remove_batch_batch_branch_classgroup'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('modules', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_semesters', to='director.branch')),
                ('semester_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_semesters', to='semester.semestertemplate')),
            ],
            options={
                'unique_together': {('branch', 'semester_template')},
            },
        ),
        migrations.CreateModel(
            name='ActiveClassSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_semesters', to='student.studentclass')),
                ('branch_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_class_semesters', to='semester.branchsemester')),
            ],
            options={
                'unique_together': {('student_class', 'branch_semester')},
            },
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='semester.branchsemester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_usages', to='semester.subject')),
            ],
            options={
                'unique_together': {('branch_semester', 'subject')},
            },
        ),
    ]
