# Generated by Django 5.1.8 on 2025-05-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0011_alter_branch_branch_name'),
        ('semester', '0001_initial'),
        ('student', '0005_alter_student_student_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activeclasssemester',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activeclasssemester',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_semesters', to='director.classgroup'),
        ),
        migrations.AlterField(
            model_name='activeclasssemester',
            name='branch_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_class_semesters', to='semester.branchsemester'),
        ),
        migrations.AlterField(
            model_name='activeclasssemester',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_semesters', to='student.studentclass'),
        ),
    ]
