# Generated by Django 5.1.8 on 2025-05-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0002_alter_activeclasssemester_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeclasssemester',
            name='student_class',
        ),
    ]
