# Generated by Django 5.1.8 on 2025-05-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0011_alter_branch_branch_name'),
        ('semester', '0003_remove_activeclasssemester_student_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activeclasssemester',
            unique_together={('class_group', 'branch_semester')},
        ),
    ]
