# Generated by Django 5.1.8 on 2025-05-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0010_remove_batch_batch_branch_classgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_roll', models.CharField(blank=True, max_length=10, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('student_phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('student_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('student_dob', models.DateField(blank=True, null=True)),
                ('student_enrollment_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('student_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='director.classgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_classes', to='student.student')),
            ],
            options={
                'unique_together': {('student', 'class_group')},
            },
        ),
    ]
