# Generated by Django 5.1.8 on 2025-05-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_batch_student_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='batch',
            new_name='student_batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='student_branch',
        ),
    ]
