# Generated by Django 5.1.8 on 2025-05-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_batch_student_student_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
