# Generated by Django 5.2 on 2025-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('institute_address', models.TextField()),
                ('institute_email', models.EmailField(max_length=254)),
                ('institute_number', models.CharField(max_length=15)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_number', models.CharField(max_length=15)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_username', models.CharField(max_length=11, unique=True)),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
    ]
