# Generated by Django 5.1.8 on 2025-05-01 08:05

import super.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='college',
            name='paid_until',
            field=models.DateField(default=super.models.default_paid_until),
        ),
    ]
