# Generated by Django 5.1.8 on 2025-05-01 08:21

import super.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_college_on_trial_college_paid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='paid_until',
            field=models.DateField(blank=True, default=super.models.default_paid_until, null=True),
        ),
    ]
