# Generated by Django 5.2 on 2025-04-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_alter_college_admin_email_alter_college_admin_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='admin_password',
            field=models.CharField(max_length=150),
        ),
    ]
